---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Include role 
      ansible.builtin.include_role:
        name: lpi_code.metatrader
      vars:
        metatrader_nb_profiles: "{{ lookup('env', 'METATRADER_NB_PROFILES') | default(1) }}"
        meta_trader_user: "{{ lookup('env', 'METATRADER_USER') | default('metatrader') }}"
        metatrader_password: "{{ lookup('env', 'METATRADER_PASSWORD') | default('metatrader') }}"
        metatrader_group: "{{ lookup('env', 'METATRADER_USER') | default('metatrader') }}"

  become: true
  become_user: root
