roles:
  - name: boutetnico.xfce
    version: 2.0.0
  
  - name: robertdebock.xrdp
    version: 2.1.9
  - name: robertdebock.bootstrap
  - name: robertdebock.core_dependencies
  - name: robertdebock.epel
collections:
  - name: community.general