roles:
  - name: webofmars.xfce4-desktop
    version: 1.1.3
  - name: robertdebock.xrdp
    version: 2.1.9
  - name: robertdebock.bootstrap
  - name: robertdebock.core_dependencies
  - name: robertdebock.epel
  - name: jakoblichterfeld.winehq
collections:
  - name: community.general