---
# tasks file for lpi-code.metatrader
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - all
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'


- name: Check if package name is gdm or gdm3
  ansible.builtin.shell: "apt search gdm | grep gdm"
  register: gdm_package
  failed_when: false
  changed_when: false

- name: Set gdm package name
  set_fact:
    gdm_package_name: "{{ 'gdm3' if 'gdm3' in gdm_package.stdout else 'gdm' }}"

- name: Remove gdm
  ansible.builtin.package:
    name: "{{ gdm_package_name }}"
    state: absent

- name: Blacklist gdm from being installed
  ansible.builtin.dpkg_selections:
    name: "{{ gdm_package_name }}"
    selection: hold

- name: Blacklist ubuntu-desktop from being installed
  ansible.builtin.dpkg_selections:
    name: ubuntu-desktop
    selection: hold
  when: ansible_distribution == 'Ubuntu'

- name: Install xfce
  ansible.builtin.include_role:
    name: webofmars.xfce4-desktop
  vars:
    xfce4_login_manager_package: lightdm
    xfce4_login_manager_service: lightdm
    xfce4_packages:
      - xserver-xorg
      - xfonts-base
      - xfce4
      - xfce4-goodies

- name: Enforce xfce session alternative
  ansible.builtin.alternatives:
    name: x-session-manager
    path: /usr/bin/xfce4-session
    link: /usr/bin/x-session-manager
    state: present
    priority: 60

- name: Install dependencies
  ansible.builtin.package:
    name: 
      - dbus-x11
      - xvfb
      - wget
    state: present

- name: Install xrdp
  ansible.builtin.include_role:
    name: robertdebock.xrdp

- name: Create group
  ansible.builtin.group:
    name: "{{ metatrader_group }}"
    state: present

- name: Add users
  ansible.builtin.user:
    name: "{{ metatrader_user }}"
    password: "{{ metatrader_password | password_hash('sha512') }}"
    group: "{{ metatrader_group }}"
    home: "{{ metatrader_home }}"
    shell: /bin/bash
    createhome: true
    state: present

- name: Create Deskop folder
  ansible.builtin.file:
    dest: "{{ metatrader_home }}/Desktop"
    state: directory
    owner: "{{ metatrader_user }}"
    group: "{{ metatrader_group }}"
    mode: '0755'

- name: Install winehq
  ansible.builtin.include_role:
    name: jakoblichterfeld.winehq
  vars:
    winehq:
      install_playonlinux: false
      install_winetricks: true
      use_devel: false
      use_staging: false

- name: Download metatrader installer and webview
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /tmp/{{ item | basename }}
    mode: '0755'
  with_items: 
    - "{{ metatrader_mt5_url }}"
    - "{{ metatrader_webview_url }}"

- name: Install metatrader profile(s)
  ansible.builtin.script:
    cmd: files/mt5.sh {{ item }}
  with_sequence: start=1 end={{ metatrader_nb_profiles }}
  loop_control:
    loop_var: item
  become: true
  become_user: "{{ metatrader_user }}"

- name: Edit desktop shortcut for Editor to include name
  ansible.builtin.replace:
    path: "{{ metatrader_home }}/Desktop/MetaEditor 5 - {{ item }}.desktop"
    regexp: 'Name=MetaEditor 5'
    replace: 'Name=MetaEditor 5 - {{ item }}'
  with_sequence: start=1 end={{ metatrader_nb_profiles }}
  loop_control:
    loop_var: item

- name: Edit desktop shortcut for Trader to include name
  ansible.builtin.replace:
    path: "{{ metatrader_home }}/Desktop/MetaTrader 5 - {{ item }}.desktop"
    regexp: 'Name=MetaTrader 5'
    replace: 'Name=MetaTrader 5 - {{ item }}'
  with_sequence: start=1 end={{ metatrader_nb_profiles }}
  loop_control:
    loop_var: item
  
