---
# tasks file for lpi-code.metatrader
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - all

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Install dependencies
  ansible.builtin.package:
    name: 
      - dbus-x11
      - xvfb
      - wget
    state: present

- name: Create polkit directory
  ansible.builtin.file:
    path: /etc/polkit-1/localauthority/50-local.d
    state: directory
    mode: '0755'
    owner: root
    group: root


- name: Set metatrader_home
  ansible.builtin.set_fact:
    metatrader_home: "/home/{{ metatrader_user }}"
  when: metatrader_home is not defined


- name: Set metatrader group
  ansible.builtin.set_fact:
    metatrader_group: "{{ metatrader_user }}"
  when: metatrader_group is not defined

- name: Create group
  ansible.builtin.group:
    name: "{{ metatrader_group }}"
    state: present


- name: Add users
  ansible.builtin.user:
    name: "{{ metatrader_user }}"
    password: "{{ metatrader_password | password_hash('sha512') }}"
    group: "{{ metatrader_group }}"
    home: "{{ metatrader_home }}"
    shell: "{{ '/bin/bash' if not metatrader_restricted else '/bin/false' }}"
    createhome: true
    state: present

- name: Create home directory
  ansible.builtin.file:
    path: "{{ metatrader_home }}"
    state: directory
    owner: "{{ metatrader_user }}"
    group: "{{ metatrader_group }}"
    mode: '0755'
  ignore_errors: true

- name: Create restricted group
  ansible.builtin.group:
    name: "{{ metatrader_restricted_group }}"
    state: present

- name: Add user to restricted group
  ansible.builtin.user:
    name: "{{ metatrader_user }}"
    group: "{{ metatrader_restricted_group }}"
    append: true
  when: metatrader_restricted

- name: Create Deskop folder
  ansible.builtin.file:
    dest: "{{ metatrader_home }}/Desktop"
    state: directory
    owner: "{{ metatrader_user }}"
    group: "{{ metatrader_group }}"
    mode: '0755'

- name: Download WineHQ GPG key
  ansible.builtin.get_url:
    url: https://dl.winehq.org/wine-builds/winehq.key
    dest: /usr/share/keyrings/winehq-archive.key
    mode: '0644'

- name: Install winehq
  ansible.builtin.include_role:
    name: jakoblichterfeld.winehq
  vars:
    winehq:
      install_playonlinux: false
      install_winetricks: true
      use_devel: false
      use_staging: false
      gpg_key_path: /usr/share/keyrings/winehq-archive.key

- name: Download metatrader installer and webview
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /tmp/{{ item | basename }}
    mode: '0755'
  with_items: 
    - "{{ metatrader_mt5_url }}"
    - "{{ metatrader_webview_url }}"

- name: Copy script to install metatrader
  ansible.builtin.copy:
    src: files/mt5.sh
    dest: /tmp/mt5.sh
    mode: '0755'
    owner: "{{ metatrader_user }}"
    group: "{{ metatrader_group }}"


- name: Install metatrader profile(s)
  ansible.builtin.shell:
    cmd: /tmp/mt5.sh {{ item }} > /tmp/mt5-{{ item }}-{{ metatrader_user }}.log
    creates: "{{ metatrader_home }}/.mt5_{{ item }}/drive_c/Program Files/MetaTrader 5/MetaEditor64.exe"
  with_sequence: start=1 end={{ metatrader_nb_profiles }}
  loop_control:
    loop_var: item
  become: true
  become_user: "{{ metatrader_user }}"

- name: Edit desktop shortcut for Editor to include name
  ansible.builtin.replace:
    path: "{{ metatrader_home }}/Desktop/MetaEditor 5 - {{ item }}.desktop"
    regexp: 'Name=MetaEditor 5'
    replace: 'Name=MetaEditor 5 - {{ item }}'
  with_sequence: start=1 end={{ metatrader_nb_profiles }}
  loop_control:
    loop_var: item

- name: Edit desktop shortcut for Trader to include name
  ansible.builtin.replace:
    path: "{{ metatrader_home }}/Desktop/MetaTrader 5 - {{ item }}.desktop"
    regexp: 'Name=MetaTrader 5'
    replace: 'Name=MetaTrader 5 - {{ item }}'
  with_sequence: start=1 end={{ metatrader_nb_profiles }}
  loop_control:
    loop_var: item

- name: Include systemctl.yml
  ansible.builtin.include_tasks: systemctl.yml
  with_sequence: start=1 end={{ metatrader_nb_profiles }}
  loop_control:
    loop_var: metatrader_instance_number