- name: Create systemd service directory for user
  file:
    path: "{{ metatrader_home }}/.config/systemd/user"
    state: directory
    owner: "{{ metatrader_user }}"
    group: "{{ metatrader_group }}"
    mode: '0755'

- name: Create metatrader service file
  template:
    dest: "{{ metatrader_home }}/.config/systemd/user/metatrader.service"
    owner: "{{ metatrader_user }}" 
    group: "{{ metatrader_group }}"
    mode: '0644'
    content: |
      [Unit]
      Description=MetaTrader Wine Service
      After=network.target
      PartOf=graphical-session.target

      [Service]
      Type=simple
      Environment=WINEPREFIX={{ metatrader_home }}/.mt5_{{ metatrader_instance_number }}
      Environment=WINEARCH=win32
      Environment=DISPLAY=:0
      ExecStart=/usr/bin/wine {{ metatrader_home }}/.mt5_{{ metatrader_instance_number }}/drive_c/Program\ Files/MetaTrader\ 5/mt5.exe
      Restart=always
      RestartSec=3

      [Install]
      WantedBy=graphical-session.target

- name: Enable lingering for metatrader user
  ansible.builtin.command: 
    cmd: "loginctl enable-linger {{ metatrader_user }}"

- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ metatrader_user }}"

- name: Enable and start metatrader service
  ansible.builtin.systemd:
    name: metatrader
    enabled: true
    state: started
    scope: user
  become: true
  become_user: "{{ metatrader_user }}"

