---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Include role 
      ansible.builtin.include_role:
        name: lpi-code.metatrader
      vars:
        metatrader_nb_profiles: 2
        metatrader_password: '123'