---
platforms:
  - name: Ubuntu-test
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    user: root
    published_ports:
      - 0.0.0.0:3389:3389
  - name: Debian-test
    image: geerlingguy/docker-debian10-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    user: root
    published_ports:
      - 0.0.0.0:3390:3389
      
driver:
  name: docker
provisioner:
  name: ansible
verifier:
  name: ansible
dependency:
  name: galaxy
  options:
    requirements-file:  requirements.yml