name: Build and Release

on:
  release:
    types: [published]
    

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller py2app

    - name: Build Windows executable
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile port_knocker.py
        mv dist/port_knocker.exe dist/YourAppName.exe

    - name: Build macOS DMG
      if: matrix.os == 'macos-latest'
      run: |
        python setup.py py2app
        hdiutil create -volname YourAppName -srcfolder dist -ov -format UDZO dist/YourAppName.dmg

    - name: Upload Windows executable
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: YourAppName-windows
        path: dist/YourAppName.exe

    - name: Upload macOS DMG
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: YourAppName-macos
        path: dist/YourAppName.dmg

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/YourAppName.exe
          dist/YourAppName.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
